# -*- coding: utf-8 -*-
"""safety_vlm_driving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORGFOfKaHYc2_NvhD2QxNsLQz6uj16lM

# Safety-Aware Post-Processing for Reliable VLM Driving Decisions
**Course: ITPG 708 | Team: Nadia, Kisaa, Sema, Hailemariam**

## Pipeline Overview
```
DriveBench Image + Question
        ↓
  Qwen2-VL-7B  (inference only, no fine-tuning)
        ↓
  Raw Action Output  (run 3 times)
        ↓
  Context Extraction  (same model, structured yes/no prompt)
        ↓
  Safety Rules Layer  (Tiers 1-4, deterministic)
        ↓
  Consistency Check   (majority vote across 3 runs)
        ↓
  Final Safe Action
```

## Cell 1: Install Dependencies
"""

# Install all required packages in one shot
# We pin transformers to 4.46.3 which is confirmed working with Qwen2-VL
!pip install -q transformers==4.46.3 accelerate safetensors
!pip install -q qwen-vl-utils
!pip install -q Pillow requests tqdm datasets
print('All packages installed!')

"""## Cell 2: Imports"""

import os
import re
import json
import random
import torch
from PIL import Image
from collections import Counter
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
from qwen_vl_utils import process_vision_info

print('Imports done.')
print(f'CUDA available: {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')

"""## Cell 3: Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile, os

# ── Unzip images from Drive to Colab local storage ──────────────────────────
zip_path   = "/content/drive/MyDrive/VLMforCars/DriveBench.zip"
extract_to = "/content/nuscenes/"

if not os.path.exists("/content/nuscenes/DriveBench"):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to)
    print("Done!")
else:
    print("Images already extracted, skipping.")

"""## Cell 4: Load DriveBench Dataset"""

from datasets import load_dataset

print('Loading DriveBench arena dataset...')
ds = load_dataset('drive-bench/arena')
ds_test = ds['test']

print(f'Total samples: {len(ds_test)}')
print(f'Question types: {Counter(ds_test["question_type"])}')

"""## Cell 5: Filter Planning Samples + Camera Logic

We keep only:
- `question_type == 'planning'`
- Exclude collision questions (out of scope for our safety framework)

**Camera selection logic:**
Each question references a specific camera in the object tag, e.g. `<c1,CAM_FRONT_LEFT,0.39,0.55>`.
We extract that camera name and use the corresponding image.
For 'safe actions' questions (no camera tag), we use CAM_FRONT as default.
"""

# ── Path to your DriveBench images on Google Drive ──────────────────────────
# Then in Cell 5, keep BASE_PATH as:
BASE_PATH = "/content/nuscenes/DriveBench/Brightness"
# Structure expected:
#   BASE_PATH/CAM_FRONT/filename.jpg
#   BASE_PATH/CAM_BACK/filename.jpg
#   BASE_PATH/CAM_FRONT_LEFT/filename.jpg  ... etc.
# ─────────────────────────────────────────────────────────────────────────────

VALID_CAMERAS = {
    'CAM_FRONT', 'CAM_BACK',
    'CAM_FRONT_LEFT', 'CAM_FRONT_RIGHT',
    'CAM_BACK_LEFT',  'CAM_BACK_RIGHT'
}

def get_camera_for_sample(question):
    """
    Extract camera name from the object tag in the question.
    Example: '<c1,CAM_FRONT_LEFT,0.39,0.55>' → 'CAM_FRONT_LEFT'
    If no tag found (e.g. 'safe actions' question) → default 'CAM_FRONT'
    """
    match = re.search(r'(CAM_FRONT_LEFT|CAM_FRONT_RIGHT|CAM_BACK_LEFT|CAM_BACK_RIGHT|CAM_FRONT|CAM_BACK)', question)
    if match:
        return match.group(1)
    return 'CAM_FRONT'   # default for 'safe actions' questions

# Filter to planning samples only, exclude collision questions
planning_samples = [
    s for s in ds_test
    if s['question_type'] == 'planning'
    and 'lead to a collision' not in s['question'].lower()
]
print(f'Planning samples (after removing collision Qs): {len(planning_samples)}')

# Keep only samples where the correct camera image actually exists on disk
valid_samples = []
missing_count = 0

for s in planning_samples:
    cam      = get_camera_for_sample(s['question'])
    filename = os.path.basename(s['image_path'][cam])
    img_path = os.path.join(BASE_PATH, cam, filename)

    if os.path.exists(img_path):
        # Store the resolved path directly for convenience
        s_copy = dict(s)
        s_copy['resolved_camera']    = cam
        s_copy['resolved_image_path'] = img_path
        valid_samples.append(s_copy)
    else:
        missing_count += 1

print(f'Valid samples (image found): {len(valid_samples)}')
print(f'Skipped (image missing):     {missing_count}')

# Show camera distribution
cam_dist = Counter(s['resolved_camera'] for s in valid_samples)
print(f'\nCamera distribution:')
for cam, count in sorted(cam_dist.items()):
    print(f'  {cam}: {count}')

"""## Cell 6: Load Qwen2-VL-7B Model
One model only. We use it for BOTH:
1. Action inference (main question)
2. Context extraction (yes/no scene questions)
"""

MODEL_ID = "Qwen/Qwen2-VL-7B-Instruct"

print(f'Loading {MODEL_ID} ...')
qwen_model = Qwen2VLForConditionalGeneration.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    device_map="auto"
)
qwen_model.eval()

qwen_processor = AutoProcessor.from_pretrained(MODEL_ID)
print('Model loaded successfully!')

"""## Cell 7: Inference Helper Functions"""

# ── Prompts ───────────────────────────────────────────────────────────────────

ACTION_SYSTEM_PROMPT = """You are an expert autonomous driving assistant analyzing a real dashcam image.
Study the scene carefully: vehicles, pedestrians, cyclists, traffic lights, road signs, lane markings.
Answer the planning question about what the ego vehicle should do.
Respond ONLY in this exact JSON format, no other text:
{"action": "<specific driving action>", "reason": "<max 5 words>"}
Action must be one of: keep speed, accelerate, brake gently, brake hard, stop, turn left, turn right, change lane left, change lane right, back up"""


CONTEXT_SYSTEM_PROMPT = """You are analyzing a dashcam image for an autonomous driving safety system.
Answer each question with ONLY the exact option given. Be precise and conservative."""


CONTEXT_USER_PROMPT = """Carefully examine this dashcam image and answer each question:

1. Is there a traffic light visible? If yes, what color is it? Answer: red / yellow / green / none
2. Is there a stop sign visible? Answer: yes / no
3. Is there a crosswalk visible? Answer: yes / no
4. Is there a pedestrian or cyclist visible in or near the road? Answer: yes / no / unsure
5. Is there a vehicle directly ahead within about 2 car lengths? Answer: yes / no / unsure
6. Is there a vehicle directly behind within about 2 car lengths? Answer: yes / no / unsure
7. Is the lane ahead blocked? Answer: yes / no / unsure
8. Is there space to change lane to the left? Answer: yes / no / unsure
9. Is there space to change lane to the right? Answer: yes / no / unsure
10. Is visibility degraded (brightness, fog, glare, night)? Answer: yes / no

Now respond ONLY with a JSON object using these exact keys:
{"traffic_light": "?", "stop_sign": "?", "crosswalk": "?", "pedestrian": "?", "vehicle_ahead": "?", "vehicle_behind": "?", "lane_blocked": "?", "drivable_left": "?", "drivable_right": "?", "visibility_degraded": "?"}"""
# ── Core inference function ───────────────────────────────────────────────────

def run_qwen(image_path: str, system_prompt: str, user_text: str,
             temperature: float = 0.2, max_new_tokens: int = 256) -> str:
    """
    Run Qwen2-VL on a single image + text prompt.
    Returns raw string output.
    """
    image_uri = "file://" + os.path.abspath(image_path)

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": [
            {"type": "image", "image": image_uri},
            {"type": "text",  "text":  user_text},
        ]},
    ]

    text_input  = qwen_processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    image_inputs, video_inputs = process_vision_info(messages)

    inputs = qwen_processor(
        text=[text_input],
        images=image_inputs,
        videos=video_inputs,
        return_tensors="pt"
    )
    inputs = {k: v.to("cuda") for k, v in inputs.items() if hasattr(v, "to")}

    with torch.no_grad():
        gen = qwen_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_p=0.9,
            do_sample=(temperature > 0)
        )

    out_tokens = gen[:, inputs["input_ids"].shape[1]:]
    return qwen_processor.batch_decode(out_tokens, skip_special_tokens=True)[0]


def parse_json_output(raw: str) -> dict:
    """Robustly extract the first JSON dict from a model response."""
    raw = raw.strip()
    # Try direct parse first
    try:
        return json.loads(raw)
    except Exception:
        pass
    # Try to find JSON block inside markdown fences or extra text
    match = re.search(r'\{[^{}]+\}', raw, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except Exception:
            pass
    return {"parse_error": True, "raw": raw}


print('Inference functions defined.')

"""## Cell 8: Action Space
We normalize all ground-truth and predicted actions into a fixed discrete set.
"""

# Discrete action space A
ACTION_SPACE = [
    'keep speed',
    'accelerate',
    'brake gently',
    'brake hard',
    'stop',
    'turn left',
    'turn right',
    'change lane left',
    'change lane right',
    'back up',
    'unknown'
]

# Keyword mapping to normalize free-form text → discrete action
ACTION_KEYWORDS = {
    'keep speed':        ['keep', 'maintain', 'same speed', 'constant', 'continue', 'going at the same'],
    'accelerate':        ['accelerat', 'speed up', 'increase speed'],
    'brake gently':      ['brake gently', 'decelerate', 'slow down', 'gradually', 'reduce speed'],
    'brake hard':        ['brake hard', 'brake sudden', 'sudden brake', 'hard brake', 'emergency'],
    'stop':              ['stop', 'halt', 'remain stationary', 'stationary', 'come to a stop'],
    'turn left':         ['turn left'],
    'turn right':        ['turn right'],
    'change lane left':  ['change lane left', 'lane change left', 'move left', 'merge left'],
    'change lane right': ['change lane right', 'lane change right', 'move right', 'merge right'],
    'back up':           ['back up', 'reverse', 'backward'],
}

# Conservative fallback order (safest first)
CONSERVATIVE_ORDER = [
    'keep speed', 'brake gently', 'brake hard', 'stop',
    'change lane left', 'change lane right', 'turn left',
    'turn right', 'accelerate', 'back up'
]
def normalize_action(text: str) -> str:
    """
    Map free-form action text to a discrete action in ACTION_SPACE.
    Tries keyword matching; returns 'unknown' if nothing matches.
    """
    text = text.lower().strip()
    for action, keywords in ACTION_KEYWORDS.items():
        for kw in keywords:
            if kw in text:
                return action
    return 'unknown'

# Quick test
test_cases = [
    ("keep going at the same speed", "keep speed"),
    ("decelerate gradually without braking", "brake gently"),
    ("remain stationary", "stop"),
    ("brake suddenly", "brake hard"),
]
print('Action normalization tests:')
for text, expected in test_cases:
    result = normalize_action(text)
    status = '✓' if result == expected else f'✗ (expected {expected})'
    print(f'  {status}  "{text}" → "{result}"')

"""## Cell 9: Safety Rules Layer (Tiers 1–4)
This is the **core contribution** of the project.
Given a predicted action + extracted context, apply hierarchical safety rules.
"""

def parse_context(context_dict: dict) -> dict:
    """
    Normalize context values to booleans / strings for rule checking.
    Handles minor variations in model output (e.g. 'yes.', 'Yes', 'RED').
    """
    def is_yes(val):
        return str(val).lower().strip().rstrip('.') in {'yes', 'true', '1'}

    def is_no(val):
        return str(val).lower().strip().rstrip('.') in {'no', 'false', '0', 'none'}

    tl = str(context_dict.get('traffic_light', 'none')).lower().strip().rstrip('.')

    return {
        'traffic_light':       tl,              # 'red','yellow','green','none'
        'stop_sign':           is_yes(context_dict.get('stop_sign', 'no')),
        'crosswalk':           is_yes(context_dict.get('crosswalk', 'no')),
        'pedestrian':          is_yes(context_dict.get('pedestrian', 'no')),
        'vehicle_ahead':       is_yes(context_dict.get('vehicle_ahead', 'no')),
        'vehicle_behind':      is_yes(context_dict.get('vehicle_behind', 'no')),
        'lane_blocked':        is_yes(context_dict.get('lane_blocked', 'no')),
        'drivable_left':       not is_no(context_dict.get('drivable_left', 'yes')),
        'drivable_right':      not is_no(context_dict.get('drivable_right', 'yes')),
        'visibility_degraded': is_yes(context_dict.get('visibility_degraded', 'no')),
    }


def apply_safety_rules(action: str, context_raw: dict) -> tuple:
    """
    Apply 4-tier safety rules to the predicted action.

    Returns:
        (safe_action, fired_rules, was_overridden)

    Tiers:
      Tier 1 – Mandatory Stop conditions
      Tier 2 – Lateral (lane change) legality
      Tier 3 – Rear-end risk
      Tier 4 – Visibility
    """
    c = parse_context(context_raw)
    fired = []   # list of rule IDs that fired

    # Build feasible action set — start with all actions, remove as rules fire
    feasible = set(ACTION_SPACE) - {'unknown'}

    # ── Tier 1: Mandatory Stop ────────────────────────────────────────────────
    # R1: Red light or stop sign → only stop-compatible actions allowed
    if c['traffic_light'] == 'red' or c['stop_sign']:
        fired.append('R1')
        feasible = feasible & {'stop', 'brake hard', 'brake gently'}

    # R2: Yellow light → no accelerating
    if c['traffic_light'] == 'yellow':
        fired.append('R2_yellow')
        feasible.discard('accelerate')

    # R3: Pedestrian or cyclist in road → ACCELERATE disallowed
    if c['pedestrian']:
        fired.append('R3')
        feasible.discard('accelerate')
        # Also disallow lane changes toward them if crosswalk present
        if c['crosswalk']:
            fired.append('R3_crosswalk')
            feasible.discard('change lane left')
            feasible.discard('change lane right')

    # R4: Lane blocked ahead → prefer braking
    if c['lane_blocked']:
        fired.append('R4')
        feasible.discard('accelerate')
        feasible.discard('keep speed')

    # ── Tier 2: Lateral Legality ──────────────────────────────────────────────
    # R5: No drivable space left → prohibit left lane change
    if not c['drivable_left']:
        fired.append('R5_left')
        feasible.discard('change lane left')

    # R6: No drivable space right → prohibit right lane change
    if not c['drivable_right']:
        fired.append('R5_right')
        feasible.discard('change lane right')

    # ── Tier 3: Rear-End Risk ─────────────────────────────────────────────────
    # R7: Vehicle behind close → avoid abrupt deceleration
    if c['vehicle_behind']:
        fired.append('R7')
        feasible.discard('brake hard')
        feasible.discard('stop')   # sudden stop dangerous with tailgater

    # ── Tier 4: Visibility ────────────────────────────────────────────────────
    # R8: Degraded visibility → no aggressive actions
    if c['visibility_degraded']:
        fired.append('R8')
        feasible.discard('accelerate')
        feasible.discard('change lane left')
        feasible.discard('change lane right')
        feasible.discard('brake hard')   # ADD THIS LINE
    # ── Check if original action is feasible ─────────────────────────────────
    if not feasible:
        # Edge case: all actions blocked — use stop as ultimate fallback
        # (if R7 fired, use brake gently instead)
        fallback = 'brake gently' if 'R7' in fired else 'stop'
        return fallback, fired, True

    if action in feasible:
        # Original action is safe — no override needed
        return action, fired, False
    else:
        # Override: pick safest action from feasible set
        for conservative_action in CONSERVATIVE_ORDER:
            if conservative_action in feasible:
                return conservative_action, fired, True
        # Fallback (should not reach here)
        return list(feasible)[0], fired, True


def is_unsafe(action: str, context_raw: dict) -> bool:
    """
    Check if an action violates any active safety rule.
    Returns True if the action is unsafe.
    """
    safe_action, fired_rules, was_overridden = apply_safety_rules(action, context_raw)
    return was_overridden


# ── Quick sanity test ─────────────────────────────────────────────────────────
print('Safety rules sanity tests:')

test1_ctx  = {'traffic_light': 'red', 'stop_sign': 'no', 'crosswalk': 'no',
               'pedestrian': 'no', 'vehicle_ahead': 'no', 'vehicle_behind': 'no',
               'lane_blocked': 'no', 'drivable_left': 'yes', 'drivable_right': 'yes',
               'visibility_degraded': 'no'}
a, rules, overridden = apply_safety_rules('accelerate', test1_ctx)
print(f'  Red light + accelerate → "{a}" | Rules: {rules} | Overridden: {overridden}')
assert overridden, 'Should be overridden!'

test2_ctx  = {'traffic_light': 'none', 'stop_sign': 'no', 'crosswalk': 'no',
               'pedestrian': 'no', 'vehicle_ahead': 'no', 'vehicle_behind': 'no',
               'lane_blocked': 'no', 'drivable_left': 'yes', 'drivable_right': 'yes',
               'visibility_degraded': 'no'}
a, rules, overridden = apply_safety_rules('keep speed', test2_ctx)
print(f'  Clear road + keep speed → "{a}" | Rules: {rules} | Overridden: {overridden}')
assert not overridden, 'Should NOT be overridden!'

test3_ctx  = {'traffic_light': 'none', 'stop_sign': 'no', 'crosswalk': 'yes',
               'pedestrian': 'yes', 'vehicle_ahead': 'no', 'vehicle_behind': 'yes',
               'lane_blocked': 'no', 'drivable_left': 'yes', 'drivable_right': 'yes',
               'visibility_degraded': 'no'}
a, rules, overridden = apply_safety_rules('accelerate', test3_ctx)
print(f'  Pedestrian on crosswalk + vehicle behind + accelerate → "{a}" | Rules: {rules} | Overridden: {overridden}')
assert overridden

print('All sanity tests passed!')

"""## Cell 10: Consistency Function
Run each sample K=3 times, apply safety rules to each, then majority vote.
"""

def consistency_vote(safe_actions: list) -> tuple:
    """
    Given K refined actions, pick the majority vote.
    If tie: pick the more conservative one.

    Returns:
        (final_action, is_consistent)
        is_consistent = True if majority agreement (>50%)
    """
    counts = Counter(safe_actions)
    most_common_action, most_common_count = counts.most_common(1)[0]
    K = len(safe_actions)

    # Majority = more than half
    is_consistent = most_common_count > K / 2

    if is_consistent:
        return most_common_action, True
    else:
        # Tie: pick most conservative from the tied actions
        tied_actions = [a for a, c in counts.items() if c == most_common_count]
        for conservative_action in CONSERVATIVE_ORDER:
            if conservative_action in tied_actions:
                return conservative_action, False
        return most_common_action, False

print('Consistency function defined.')

"""## Cell 11: Main Evaluation Loop

For each sample:
1. Extract context (1 call to Qwen)
2. Run action inference K=3 times (3 calls to Qwen)
3. Apply safety rules to each run
4. Majority vote → final action
5. Record everything

"""

K             = 3     # number of inference runs per sample for consistency
NUM_SAMPLES   = 400   # set to len(valid_samples) for full run
SAVE_PATH     = "/content/drive/MyDrive/vlm_driving_results.json"

random.seed(42)
eval_samples = random.sample(valid_samples, min(NUM_SAMPLES, len(valid_samples)))

results = []

for i, sample in enumerate(tqdm(eval_samples, desc='Evaluating')):
    img_path  = sample['resolved_image_path']
    cam       = sample['resolved_camera']
    question  = sample['question']
    gt_text   = sample['answer']
    gt_action = normalize_action(gt_text)

    # ── Step 1: Context Extraction (1 call) ───────────────────────────────────
    try:
        ctx_raw = run_qwen(
            img_path,
            CONTEXT_SYSTEM_PROMPT,
            CONTEXT_USER_PROMPT,
            temperature=0.0,   # deterministic for context
            max_new_tokens=128
        )
        context_dict = parse_json_output(ctx_raw)
        context_ok   = 'parse_error' not in context_dict
    except Exception as e:
        context_dict = {}
        context_ok   = False
        print(f'  [WARNING] Context extraction failed for sample {i+1}: {e}')

    # ── Step 2: Action Inference × K runs ─────────────────────────────────────
    raw_outputs     = []   # raw text from model
    baseline_actions = []  # normalized, before safety
    safe_actions    = []   # after safety rules
    fired_rules_all = []   # rules that fired per run
    overrides       = []   # was this run overridden?

    for k in range(K):
        try:
            raw = run_qwen(
                img_path,
                ACTION_SYSTEM_PROMPT,
                question,
                temperature=0.7,
                max_new_tokens=128
            )
            parsed    = parse_json_output(raw)
            action_text = parsed.get('action', 'unknown') if 'parse_error' not in parsed else 'unknown'
            baseline_action = normalize_action(action_text)

        except Exception as e:
            raw             = ''
            baseline_action = 'unknown'

        # Apply safety rules
        if context_ok and baseline_action != 'unknown':
            safe_action, fired, overridden = apply_safety_rules(baseline_action, context_dict)
        else:
            # No valid context → keep baseline, flag as no override
            safe_action = baseline_action
            fired       = []
            overridden  = False

        raw_outputs.append(raw)
        baseline_actions.append(baseline_action)
        safe_actions.append(safe_action)
        fired_rules_all.extend(fired)
        overrides.append(overridden)

    # ── Step 3: Consistency Vote ───────────────────────────────────────────────
    # Baseline consistency (before safety)
    baseline_final, baseline_consistent = consistency_vote(baseline_actions)
    # Safe consistency (after safety)
    safe_final, safe_consistent         = consistency_vote(safe_actions)

    # ── Step 4: Unsafe check on final outputs ─────────────────────────────────
    baseline_unsafe = is_unsafe(baseline_final, context_dict) if context_ok else False
    safe_unsafe     = is_unsafe(safe_final, context_dict)     if context_ok else False

    # ── Step 5: Accuracy check ────────────────────────────────────────────────
    baseline_correct = (baseline_final == gt_action)
    safe_correct     = (safe_final     == gt_action)

    # ── Store Result ──────────────────────────────────────────────────────────
    result = {
        'sample_id':          i + 1,
        'image_file':         os.path.basename(img_path),
        'camera':             cam,
        'question':           question,
        'ground_truth_text':  gt_text,
        'ground_truth_action': gt_action,

        # Context
        'context':            context_dict,
        'context_ok':         context_ok,

        # Baseline (before safety)
        'baseline_actions_k':   baseline_actions,
        'baseline_final':       baseline_final,
        'baseline_consistent':  baseline_consistent,
        'baseline_unsafe':      baseline_unsafe,
        'baseline_correct':     baseline_correct,

        # After safety layer
        'safe_actions_k':    safe_actions,
        'safe_final':        safe_final,
        'safe_consistent':   safe_consistent,
        'safe_unsafe':       safe_unsafe,
        'safe_correct':      safe_correct,

        # Override info
        'any_override':      any(overrides),
        'fired_rules':       list(set(fired_rules_all)),
    }
    results.append(result)

    # Save checkpoint every 10 samples
    if (i + 1) % 10 == 0:
        with open(SAVE_PATH, 'w') as f:
            json.dump(results, f, indent=2)
        print(f'Checkpoint saved at sample {i+1}')

# Final save
with open(SAVE_PATH, 'w') as f:
    json.dump(results, f, indent=2)
print(f'\nDone! Results saved to {SAVE_PATH}')

"""## Cell 12: Compute All 4 Evaluation Metrics"""

# ── Load results (if re-running from saved file) ──────────────────────────────
# with open(SAVE_PATH) as f:
#     results = json.load(f)

# Filter to samples where context extraction worked
valid_results = [r for r in results if r['context_ok'] and r['ground_truth_action'] != 'unknown']
N = len(valid_results)
print(f'Evaluating on {N} valid samples (out of {len(results)} total)')

# ── Metric 1: Decision Accuracy ───────────────────────────────────────────────
baseline_acc = sum(r['baseline_correct'] for r in valid_results) / N
safe_acc     = sum(r['safe_correct']     for r in valid_results) / N

# ── Metric 2: Unsafe Decision Rate ───────────────────────────────────────────
baseline_unsafe_rate = sum(r['baseline_unsafe'] for r in valid_results) / N
safe_unsafe_rate     = sum(r['safe_unsafe']     for r in valid_results) / N

# ── Metric 3: False Override Rate ────────────────────────────────────────────
# False override = baseline was correct BUT safe final changed it to wrong
false_overrides = sum(
    1 for r in valid_results
    if r['baseline_correct'] and not r['safe_correct'] and r['any_override']
)
false_override_rate = false_overrides / N

# ── Metric 4: Consistency Score ───────────────────────────────────────────────
baseline_consistency = sum(r['baseline_consistent'] for r in valid_results) / N
safe_consistency     = sum(r['safe_consistent']     for r in valid_results) / N

# ── Summary Table ─────────────────────────────────────────────────────────────
print('\n' + '='*60)
print('RESULTS SUMMARY')
print('='*60)
print(f'{"Metric":<30} {"Baseline":>12} {"After Safety":>14}')
print('-'*60)
print(f'{"Decision Accuracy":<30} {baseline_acc:>11.1%} {safe_acc:>13.1%}')
print(f'{"Unsafe Decision Rate":<30} {baseline_unsafe_rate:>11.1%} {safe_unsafe_rate:>13.1%}')
print(f'{"Consistency Score":<30} {baseline_consistency:>11.1%} {safe_consistency:>13.1%}')
print(f'{"False Override Rate":<30} {"—":>12} {false_override_rate:>13.1%}')
print('='*60)
print(f'\nTotal overrides applied: {sum(1 for r in valid_results if r["any_override"])}')
print(f'Unsafe rate reduction:   {(baseline_unsafe_rate - safe_unsafe_rate):.1%}')
print(f'Accuracy change:         {(safe_acc - baseline_acc):+.1%}')

"""## Cell 13: Rule Firing Analysis"""

# Count how many times each rule fired across all samples
all_fired = []
for r in valid_results:
    all_fired.extend(r['fired_rules'])

rule_counts = Counter(all_fired)

rule_names = {
    'R1':          'T1: Red light / Stop sign',
    'R2_yellow':   'T1: Yellow light',
    'R3':          'T1: Pedestrian/Cyclist in road',
    'R3_crosswalk':'T1: Pedestrian on crosswalk',
    'R4':          'T1: Lane blocked',
    'R5_left':     'T2: No space left',
    'R5_right':    'T2: No space right',
    'R7':          'T3: Vehicle behind close',
    'R8':          'T4: Degraded visibility',
}

print('Rule Firing Counts:')
print('-'*50)
total_fires = sum(rule_counts.values())
for rule_id, rule_name in rule_names.items():
    count = rule_counts.get(rule_id, 0)
    pct   = count / N * 100
    print(f'  {rule_id:<15} {rule_name:<35} {count:>4}x  ({pct:.1f}% of samples)')
print(f'  {"TOTAL":<50} {total_fires:>4}x')

"""## Cell 14: Visualizations"""

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle('Safety-Aware Post-Processing Results', fontsize=14, fontweight='bold')

colors_base = '#FFB3BA'   # pastel red
colors_safe = '#B5EAD7'   # pastel green
# ── Plot 1: Unsafe Rate ───────────────────────────────────────────────────────
ax = axes[0]
bars = ax.bar(['Baseline', 'After Safety'],
              [baseline_unsafe_rate * 100, safe_unsafe_rate * 100],
              color=[colors_base, colors_safe], width=0.5, edgecolor='black')
ax.set_title('Unsafe Decision Rate', fontweight='bold')
ax.set_ylabel('Percentage (%)')
ax.set_ylim(0, max(baseline_unsafe_rate * 100 * 1.3, 10))
for bar in bars:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
            f'{bar.get_height():.1f}%', ha='center', va='bottom', fontweight='bold')

# ── Plot 2: Accuracy ─────────────────────────────────────────────────────────
ax = axes[1]
bars = ax.bar(['Baseline', 'After Safety'],
              [baseline_acc * 100, safe_acc * 100],
              color=[colors_base, colors_safe], width=0.5, edgecolor='black')
ax.set_title('Decision Accuracy', fontweight='bold')
ax.set_ylabel('Percentage (%)')
ax.set_ylim(0, 100)
for bar in bars:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
            f'{bar.get_height():.1f}%', ha='center', va='bottom', fontweight='bold')

# ── Plot 3: Consistency Score ─────────────────────────────────────────────────
ax = axes[2]
bars = ax.bar(['Baseline', 'After Safety'],
              [baseline_consistency * 100, safe_consistency * 100],
              color=[colors_base, colors_safe], width=0.5, edgecolor='black')
ax.set_title('Consistency Score', fontweight='bold')
ax.set_ylabel('Percentage (%)')
ax.set_ylim(0, 100)
for bar in bars:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
            f'{bar.get_height():.1f}%', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/vlm_results_chart.png', dpi=150, bbox_inches='tight')
plt.show()
print('Chart saved.')

"""## Cell 15: Error Categorization Analysis"""

import json
with open('/content/drive/MyDrive/vlm_driving_results.json') as f:
    results = json.load(f)
print(f'Loaded {len(results)} results')

from collections import Counter
import matplotlib.pyplot as plt

total = len(results)

# Error Type 1: Context Extraction Errors
# context_ok == False → safety rules couldn't fire at all
n_ctx = sum(1 for r in results if not r['context_ok'])

# Error Type 2: Rule Conflicts
# Rules fired but overrode a correct baseline → wrong safe action
n_rule = sum(
    1 for r in results
    if r['context_ok'] and r['any_override']
    and r['baseline_correct'] and not r['safe_correct']
)

# Error Type 3: Ambiguous Scenes
# Model inconsistent across K=3 runs (not already a rule conflict)
n_ambig = sum(
    1 for r in results
    if r['context_ok']
    and not r['baseline_consistent']
    and not (r['any_override'] and r['baseline_correct'] and not r['safe_correct'])
)

# ── Print Table ───────────────────────────────────────────────────────────────
print('=' * 55)
print('ERROR CATEGORIZATION')
print('=' * 55)
print(f'{"Error Type":<30} {"Count":>6}  {"% of Total":>10}')
print('-' * 55)
print(f'{"1. Context Extraction Errors":<30} {n_ctx:>6}  {n_ctx/total*100:>9.1f}%')
print(f'{"2. Rule Conflicts":<30} {n_rule:>6}  {n_rule/total*100:>9.1f}%')
print(f'{"3. Ambiguous Scenes":<30} {n_ambig:>6}  {n_ambig/total*100:>9.1f}%')
print('-' * 55)
total_cat = n_ctx + n_rule + n_ambig
print(f'{"Total categorized":<30} {total_cat:>6}  {total_cat/total*100:>9.1f}%')
print('=' * 55)

# ── Error Categorization - Better Visualization ───────────────────────────────
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

total = len(results)

n_ctx   = sum(1 for r in results if not r['context_ok'])
n_rule  = sum(1 for r in results if r['context_ok'] and r['any_override']
              and r['baseline_correct'] and not r['safe_correct'])
n_ambig = sum(1 for r in results if r['context_ok'] and not r['baseline_consistent']
              and not (r['any_override'] and r['baseline_correct'] and not r['safe_correct']))

labels  = ['Context\nExtraction\nErrors', 'Rule\nConflicts', 'Ambiguous\nScenes']
counts  = [n_ctx, n_rule, n_ambig]
colors  = ['#4C9BE8', '#E8714C', '#4CE8A0']
total_cat = sum(counts)

fig = plt.figure(figsize=(16, 6))
fig.patch.set_facecolor('#F8F9FA')

# ── Plot 1: Horizontal bar ────────────────────────────────────────────────────
ax1 = fig.add_subplot(1, 3, 1)
ax1.set_facecolor('#F8F9FA')

y_pos = np.arange(len(labels))
bars = ax1.barh(y_pos, counts, color=colors, edgecolor='white',
                height=0.5, linewidth=1.5)

# Annotate bars
for bar, c in zip(bars, counts):
    ax1.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
             f'{c}  ({c/total*100:.1f}%)',
             va='center', fontsize=11, fontweight='bold', color='#333333')

ax1.set_yticks(y_pos)
ax1.set_yticklabels(['Context\nExtraction', 'Rule\nConflicts', 'Ambiguous\nScenes'],
                     fontsize=10)
ax1.set_xlabel('Number of Samples', fontsize=10)
ax1.set_title('Error Counts', fontsize=12, fontweight='bold', pad=12)
ax1.set_xlim(0, max(counts) * 1.6 if max(counts) > 0 else 10)
ax1.spines[['top', 'right', 'left']].set_visible(False)
ax1.xaxis.grid(True, linestyle='--', alpha=0.5)
ax1.set_axisbelow(True)

# ── Plot 2: Donut chart ───────────────────────────────────────────────────────
ax2 = fig.add_subplot(1, 3, 2)
ax2.set_facecolor('#F8F9FA')

wedge_props = {'linewidth': 2, 'edgecolor': 'white'}
wedges, texts, autotexts = ax2.pie(
    counts,
    colors=colors,
    autopct=lambda p: f'{p:.1f}%' if p > 0 else '',
    startangle=90,
    wedgeprops={**wedge_props, 'width': 0.55},   # donut
    pctdistance=0.75,
    textprops={'fontsize': 11, 'fontweight': 'bold'}
)
for at in autotexts:
    at.set_color('white')

# Center text
ax2.text(0, 0, f'{total_cat}\nerrors', ha='center', va='center',
         fontsize=13, fontweight='bold', color='#333333')

ax2.set_title('Distribution', fontsize=12, fontweight='bold', pad=12)
legend_patches = [mpatches.Patch(color=c, label=f'{l.replace(chr(10), " ")} ({v})')
                  for c, l, v in zip(colors, labels, counts)]
ax2.legend(handles=legend_patches, loc='lower center',
           bbox_to_anchor=(0.5, -0.15), fontsize=9, frameon=False)

# ── Plot 3: % of total stacked context ────────────────────────────────────────
ax3 = fig.add_subplot(1, 3, 3)
ax3.set_facecolor('#F8F9FA')

pcts = [c / total * 100 for c in counts]
remaining = 100 - sum(pcts)

bar_width = 0.35
bottom = 0
for pct, color, label in zip(pcts, colors, labels):
    ax3.bar(0, pct, bar_width, bottom=bottom, color=color,
            edgecolor='white', linewidth=1.5,
            label=f'{label.replace(chr(10), " ")}: {pct:.1f}%')
    if pct > 0.5:
        ax3.text(0, bottom + pct/2, f'{pct:.1f}%',
                 ha='center', va='center', fontsize=11,
                 fontweight='bold', color='white')
    bottom += pct

ax3.bar(0, remaining, bar_width, bottom=bottom,
        color='#E0E0E0', edgecolor='white', linewidth=1.5, label=f'No Error: {remaining:.1f}%')
ax3.text(0, bottom + remaining/2, f'{remaining:.1f}%',
         ha='center', va='center', fontsize=11, fontweight='bold', color='#888888')

ax3.set_xlim(-0.5, 0.5)
ax3.set_ylim(0, 100)
ax3.set_ylabel('% of Total Samples', fontsize=10)
ax3.set_title('Error vs Clean', fontsize=12, fontweight='bold', pad=12)
ax3.set_xticks([])
ax3.spines[['top', 'right', 'bottom', 'left']].set_visible(False)
ax3.legend(loc='lower center', bbox_to_anchor=(0.5, -0.22),
           fontsize=8.5, frameon=False, ncol=1)

plt.suptitle('Error Categorization Analysis', fontsize=14,
             fontweight='bold', color='#222222', y=1.02)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/vlm_error_categorization.png',
            dpi=150, bbox_inches='tight', facecolor='#F8F9FA')
plt.show()

"""## Cell 16: Rule Firing Bar Chart"""

fig, ax = plt.subplots(figsize=(10, 5))

labels = [rule_names.get(r, r) for r in rule_names.keys()]
counts = [rule_counts.get(r, 0) for r in rule_names.keys()]
pastels = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9', '#BAE1FF',
           '#E3BAFF', '#C9C9FF', '#FFD1DC', '#D5E8D4']

bars = ax.barh(labels, counts, color=pastels[:len(labels)], edgecolor='black')
ax.set_xlabel('Number of samples where rule fired')
ax.set_title('Safety Rule Activation Frequency', fontweight='bold')

for bar, count in zip(bars, counts):
    ax.text(bar.get_width() + 0.2, bar.get_y() + bar.get_height()/2,
            str(count), va='center', fontweight='bold')

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/vlm_rule_chart.png', dpi=150, bbox_inches='tight')
plt.show()
print('Rule chart saved.')

"""## Cell 17: Qualitative Examples
Show 5 interesting cases where the safety layer fired.
"""

# ── Cell 16: Qualitative Examples ────────────────────────────────────────────
# Show 5 interesting cases where the safety layer fired

override_samples = [r for r in valid_results if r['any_override']]
print(f'Total samples with at least one override: {len(override_samples)}')

# Pick up to 5 to display
show = override_samples[:5]

fig, axes = plt.subplots(len(show), 2, figsize=(14, 5 * len(show)))

for idx, r in enumerate(show):
    ax_img  = axes[idx][0]
    ax_text = axes[idx][1]

    # ── Left: show the actual image ───────────────────────────────────────────
    img_path = r['resolved_image_path'] if 'resolved_image_path' in r else None

    # If resolved_image_path not stored in results, rebuild it from valid_samples
    if img_path is None:
        match = next(
            (s for s in valid_samples
             if os.path.basename(s['resolved_image_path']) == r['image_file']),
            None
        )
        img_path = match['resolved_image_path'] if match else None

    if img_path and os.path.exists(img_path):
        img = Image.open(img_path)
        ax_img.imshow(img)
        ax_img.set_title(f"Sample {r['sample_id']} | Camera: {r['camera']}", fontsize=10, fontweight='bold')
    else:
        ax_img.text(0.5, 0.5, 'Image not found', ha='center', va='center')
        ax_img.set_title(f"Sample {r['sample_id']} | Camera: {r['camera']}", fontsize=10)

    ax_img.axis('off')

    # ── Right: show the decision details ─────────────────────────────────────
    ax_text.axis('off')

    # Color coding
    baseline_color = 'red'   if r['baseline_unsafe'] else 'green'
    safe_color     = 'green' if not r['safe_unsafe']  else 'red'

    lines = [
        ("QUESTION", r['question'], 'black'),
        ("", "", 'black'),
        ("GROUND TRUTH",  r['ground_truth_action'].upper(), 'blue'),
        ("", "", 'black'),
        ("QWEN RAW",      r['baseline_final'].upper(),  baseline_color),
        ("RULES FIRED",   ', '.join(r['fired_rules']) if r['fired_rules'] else 'none', 'darkorange'),
        ("AFTER SAFETY",  r['safe_final'].upper(),      safe_color),
        ("", "", 'black'),
        ("Baseline correct?", "✓ Yes" if r['baseline_correct'] else "✗ No",
         'green' if r['baseline_correct'] else 'red'),
        ("Safe correct?",     "✓ Yes" if r['safe_correct']     else "✗ No",
         'green' if r['safe_correct']     else 'red'),
    ]

    y = 0.95
    for label, value, color in lines:
        if label == "":
            y -= 0.04
            continue
        ax_text.text(0.0, y, f"{label}:", fontsize=9,
                     fontweight='bold', transform=ax_text.transAxes,
                     verticalalignment='top', color='black')
        ax_text.text(0.42, y, value, fontsize=9,
                     transform=ax_text.transAxes,
                     verticalalignment='top', color=color,
                     wrap=True)
        y -= 0.09

plt.suptitle('Qualitative Examples: Safety Override Cases', fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/vlm_qualitative_examples.png', dpi=150, bbox_inches='tight')
plt.show()
print('Qualitative figure saved to Drive.')

